apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: my-app  # Selector to match pods
  template:
    metadata:
      labels:
        app: my-app  # Label for pods
    spec:
      containers:
        - name: my-app-container
          image: nginx:1.21.6  # Image to run
          ports:
            - containerPort: 80  # Port the container listens on
          env:  # Environment variables
            - name: ENVIRONMENT
              value: "production"
          resources:  # Resource requests and limits
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:  # Readiness probe configuration
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:  # Liveness probe configuration
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
