apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx-deployment
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest  # Use the latest NGINX image
          ports:
            - containerPort: 80  # Container will listen on port 80
